// This file is automatically generated by vscode-react-native@0.2.4
// Please do not modify it manually. All changes will be lost.
var React = require('/Users/farazkhan/Documents/personal-projects/marauders-map-native/node_modules/react');
var {Component} = React;

var ReactNative = require('/Users/farazkhan/Documents/personal-projects/marauders-map-native/node_modules/react-native');
var {AppRegistry} = ReactNative;

var entryPoint = require('/Users/farazkhan/Documents/personal-projects/marauders-map-native/main.js');

AppRegistry.registerRunnable('main', function(appParameters) {
    AppRegistry.runApplication('marauders-map-native', appParameters);
});